numstr = input('Introduce 3 números separados por comas (Ej. 33, 72, 88): ').split(', ') #El usuario introduce los números, y nosotros lo convertimos en una lista
lnum = [] #Esta es la variable con números que son números y no strings
for i in numstr: #Por cada elemento de la lista de números que son string...
    n = float(i) #Lo convertimos a un número decimal...
    lnum.append(n) #Y lo metemos en la lista de números

lnum = sorted(lnum)[::-1] #Ordenamos la lista (el método sorted() devuelve la lista de números de menor a mayor) y le damos la vuelta para que sea de mayor a menor
nstr = [] #Esta es la variable con los números hechos cadena
for i in lnum: #Por cada número en la lista de números ordenada...
    n = str(i) #Lo convertimos a string...
    nstr.append(n) #Y finalmente, los metemos en la lista de números strings
nstr = " ".join(nstr) #Y por último, ponemos los números en una sola cadena separados por espacios
print(f'Los números introducidos de mayor a menor son: {nstr}')